python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset pg19 --prefix_len 8224
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset pg19 --prefix_len 8224
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.06 --dataset pg19 --prefix_len 8224
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 8224
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset pg19 --prefix_len 16416
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset pg19 --prefix_len 16416
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.06 --dataset pg19 --prefix_len 16416
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 16416
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset pg19 --prefix_len 32800
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset pg19 --prefix_len 32800
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.06 --dataset pg19 --prefix_len 32800
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 32800
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.06 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568

python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.35 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.50 --dataset pg19 --prefix_len 65568

python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.50 --dataset longbenchv1 --task qmsum
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.35 --dataset longbenchv1 --task qmsum
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.06 --dataset longbenchv1 --task qmsum
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset longbenchv1 --task qmsum
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.50 --dataset longbenchv1 --task gov_report
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.35 --dataset longbenchv1 --task gov_report
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task gov_report
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task gov_report
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.06 --dataset longbenchv1 --task gov_report
python tests/RetrievalAttention/selfspec_benchmark.py --model_name Llama-3.2-3B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset longbenchv1 --task gov_report