# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 8224 --max_len 8320 --draft_budget 257 
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 8224 --max_len 8320 --draft_budget 513 
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 8224 --max_len 8320 --draft_budget 1025 
python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 8224 --max_len 8320 --draft_budget 2049 

# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 8224 --max_len 8320 --draft_budget 8193 

python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 16416 --max_len 16512 --draft_budget 513 
python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 16416 --max_len 16512 --draft_budget 1025 
python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 16416 --max_len 16512 --draft_budget 2049 
python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 16416 --max_len 16512 --draft_budget 4097 

python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 32800 --max_len 32896 --draft_budget 1025 
python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 32800 --max_len 32896 --draft_budget 2049 
python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 32800 --max_len 32896 --draft_budget 4097 
python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 32800 --max_len 32896 --draft_budget 8193 

python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 65568 --max_len 65664 --draft_budget 2049 
python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 65568 --max_len 65664 --draft_budget 4097 
python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 65568 --max_len 65664 --draft_budget 8193 
python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 65568 --max_len 65664 --draft_budget 16385 

# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 513 --chunk_size 16  --dataset longbenchv1 --task qmsum --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 1025 --chunk_size 16  --dataset longbenchv1 --task qmsum --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 2049 --chunk_size 16  --dataset longbenchv1 --task qmsum --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 4097 --chunk_size 16  --dataset longbenchv1 --task qmsum --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 513 --chunk_size 16  --dataset longbenchv1 --task gov_report --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 1025 --chunk_size 16  --dataset longbenchv1 --task gov_report --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 2049 --chunk_size 16  --dataset longbenchv1 --task gov_report --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 4097 --chunk_size 16  --dataset longbenchv1 --task gov_report --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 129 --chunk_size 16  --dataset longbenchv1 --task multi_news --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 257 --chunk_size 16  --dataset longbenchv1 --task multi_news --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 513 --chunk_size 16  --dataset longbenchv1 --task multi_news --compile
# python tests/selfspec_benchmark_common.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --quest --latest_k 128 --rank_group 0 1 --gamma 16 --B 1 --draft_budget 1025 --chunk_size 16  --dataset longbenchv1 --task multi_news --compile