python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 513 --chunk_size 16  --dataset longbenchv1 --task qmsum 
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 1025 --chunk_size 16  --dataset longbenchv1 --task qmsum 
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 2049 --chunk_size 16  --dataset longbenchv1 --task qmsum 
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 4097 --chunk_size 16  --dataset longbenchv1 --task qmsum 
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 513 --chunk_size 16  --dataset longbenchv1 --task gov_report 
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 1025 --chunk_size 16  --dataset longbenchv1 --task gov_report 
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 2049 --chunk_size 16  --dataset longbenchv1 --task gov_report 
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 4097 --chunk_size 16  --dataset longbenchv1 --task gov_report 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 129 --chunk_size 16  --dataset longbenchv1 --task multi_news 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 257 --chunk_size 16  --dataset longbenchv1 --task multi_news 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 513 --chunk_size 16  --dataset longbenchv1 --task multi_news 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --draft_budget 1025 --chunk_size 16  --dataset longbenchv1 --task multi_news 