# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 8224 --max_len 8320 --chunk_size 8 --draft_budget 257 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 8224 --max_len 8320 --chunk_size 8 --draft_budget 513 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 8224 --max_len 8320 --chunk_size 8 --draft_budget 1025 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 8224 --max_len 8320 --chunk_size 8 --draft_budget 2049 

# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 16416 --max_len 16512 --chunk_size 8 --draft_budget 513 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 16416 --max_len 16512 --chunk_size 8 --draft_budget 1025 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 16416 --max_len 16512 --chunk_size 8 --draft_budget 2049 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 16416 --max_len 16512 --chunk_size 8 --draft_budget 4097 

# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 32800 --max_len 32896 --chunk_size 8 --draft_budget 1025 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 32800 --max_len 32896 --chunk_size 8 --draft_budget 2049 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 32800 --max_len 32896 --chunk_size 8 --draft_budget 4097 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 32800 --max_len 32896 --chunk_size 8 --draft_budget 8193 

# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 65568 --max_len 65664 --chunk_size 8 --draft_budget 2049 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 65568 --max_len 65664 --chunk_size 8 --draft_budget 4097 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 65568 --max_len 65664 --chunk_size 8 --draft_budget 8193 
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --prefix_len 65568 --max_len 65664 --chunk_size 8 --draft_budget 16385 

python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --chunk_size 16 --draft_budget 257  --dataset longbenchv1 --task qmsum
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --chunk_size 16 --draft_budget 513  --dataset longbenchv1 --task qmsum
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --chunk_size 16 --draft_budget 1025  --dataset longbenchv1 --task qmsum
# python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --chunk_size 16 --draft_budget 2049  --dataset longbenchv1 --task qmsum
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --chunk_size 16 --draft_budget 257  --dataset longbenchv1 --task gov_report
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --chunk_size 16 --draft_budget 513  --dataset longbenchv1 --task gov_report
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --chunk_size 16 --draft_budget 1025  --dataset longbenchv1 --task gov_report
python tests/Quest/selfspec_benchmark.py --model checkpoints/meta-llama/Meta-Llama-3.1-8B/model.pth --model_name meta-llama/Meta-Llama-3.1-8B --latest_k 128 --rank_group 0 --gamma 16 --B 1 --chunk_size 16 --draft_budget 2049  --dataset longbenchv1 --task gov_report