CLUSTER_SIZE=16 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset pg19 --prefix_len 65568
CLUSTER_SIZE=16 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset pg19 --prefix_len 65568
CLUSTER_SIZE=64 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset pg19 --prefix_len 65568
CLUSTER_SIZE=64 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset pg19 --prefix_len 65568

CLUSTER_SIZE=16 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
CLUSTER_SIZE=64 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
CLUSTER_SIZE=128 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
CLUSTER_SIZE=16 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
CLUSTER_SIZE=64 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum
CLUSTER_SIZE=128 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.25 --dataset longbenchv1 --task qmsum

CLUSTER_SIZE=16 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
CLUSTER_SIZE=64 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
CLUSTER_SIZE=128 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
CLUSTER_SIZE=16 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=16 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=32 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=64 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
CLUSTER_SIZE=64 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=10 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=20 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
# CLUSTER_SIZE=128 NUM_ITERS=40 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
CLUSTER_SIZE=128 NUM_ITERS=80 python tests/RetrievalAttention/selfspec_benchmark.py --model_name Meta-Llama-3.1-8B  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.12 --dataset longbenchv1 --task qmsum
