python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate

python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate

python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.25KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 32 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate

# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 16 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate

# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_16385_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_32769_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.12KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.06KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate
# python simulator.py --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --planes_per_die 8 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/data_superclustersize_4_0.03KV_65537_clustersize_16 --num_heads 8 --cluster_size 16 --hot_cluster_ratio 0.01 --max_latency_calculate --hot_cluster_duplicate