#!/bin/bash

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 8193 --budget_ratio 0.06 --hot_cluster_ratio 0.01 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 8193 --budget_ratio 0.06 --hot_cluster_ratio 0.01 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 8193 --budget_ratio 0.06 --hot_cluster_ratio 0.02 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 8193 --budget_ratio 0.06 --hot_cluster_ratio 0.02 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 8193 --budget_ratio 0.06 --hot_cluster_ratio 0.04 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 8193 --budget_ratio 0.06 --hot_cluster_ratio 0.04 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 8193 --budget_ratio 0.06 --hot_cluster_ratio 0.08 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 8193 --budget_ratio 0.06 --hot_cluster_ratio 0.08 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 8193 --budget_ratio 0.06 --hot_cluster_ratio 0.16 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 8193 --budget_ratio 0.06 --hot_cluster_ratio 0.16 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 16385 --budget_ratio 0.06 --hot_cluster_ratio 0.01 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 16385 --budget_ratio 0.06 --hot_cluster_ratio 0.01 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 16385 --budget_ratio 0.06 --hot_cluster_ratio 0.02 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 16385 --budget_ratio 0.06 --hot_cluster_ratio 0.02 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 16385 --budget_ratio 0.06 --hot_cluster_ratio 0.04 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 16385 --budget_ratio 0.06 --hot_cluster_ratio 0.04 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 16385 --budget_ratio 0.06 --hot_cluster_ratio 0.08 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 16385 --budget_ratio 0.06 --hot_cluster_ratio 0.08 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 16385 --budget_ratio 0.06 --hot_cluster_ratio 0.16 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 16385 --budget_ratio 0.06 --hot_cluster_ratio 0.16 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 32769 --budget_ratio 0.06 --hot_cluster_ratio 0.01 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 32769 --budget_ratio 0.06 --hot_cluster_ratio 0.01 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 32769 --budget_ratio 0.06 --hot_cluster_ratio 0.02 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 32769 --budget_ratio 0.06 --hot_cluster_ratio 0.02 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 32769 --budget_ratio 0.06 --hot_cluster_ratio 0.04 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 32769 --budget_ratio 0.06 --hot_cluster_ratio 0.04 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 32769 --budget_ratio 0.06 --hot_cluster_ratio 0.08 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 32769 --budget_ratio 0.06 --hot_cluster_ratio 0.08 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 32769 --budget_ratio 0.06 --hot_cluster_ratio 0.16 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 32769 --budget_ratio 0.06 --hot_cluster_ratio 0.16 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 65537 --budget_ratio 0.06 --hot_cluster_ratio 0.01 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 65537 --budget_ratio 0.06 --hot_cluster_ratio 0.01 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 65537 --budget_ratio 0.06 --hot_cluster_ratio 0.02 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 65537 --budget_ratio 0.06 --hot_cluster_ratio 0.02 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 65537 --budget_ratio 0.06 --hot_cluster_ratio 0.04 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 65537 --budget_ratio 0.06 --hot_cluster_ratio 0.04 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 65537 --budget_ratio 0.06 --hot_cluster_ratio 0.08 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 65537 --budget_ratio 0.06 --hot_cluster_ratio 0.08 --planes_per_die 32 --hot_cluster_duplicate

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 65537 --budget_ratio 0.06 --hot_cluster_ratio 0.16 --planes_per_die 32

python simulator.py --max_latency_calculate --csv_path num_replica_4_budget_ratio_0.06_planes_per_die_32 --num_channels 1 --chips_per_channel 1 --dies_per_chip 1 --page_size_bytes 4096 --vector_bytes 4 --flash_read_latency_us 50 --num_heads 8 --cluster_size 16 --window_size 64 --profiling_dir /home/juchanlee/MagicDec/Engine/RetrievalAttention/profile/data/ --num_replica 4 --prefix_len 65537 --budget_ratio 0.06 --hot_cluster_ratio 0.16 --planes_per_die 32 --hot_cluster_duplicate