python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
python tests/RetrievalAttention/selfspec_benchmark.py --model_name qwen2.5-32b  --gamma 64 --B 1 --attn_type RetroInfer --budget_ratio 0.03 --dataset pg19 --prefix_len 65568
